#!/bin/bash
set -euo pipefail
# actool won't accept a relative path for the .icon document (fails with "couldn't be opened"),
# so resolve one absolute root to build every path from. Assumes this script is run from repo root.
ROOT="$(cd "$(dirname "$0")" && pwd)"

echo "Copying app skeleton... 🦴"
rm -rf ./QWebSyphon.app
cp -r app_bundler/QWebSyphon.app.skeleton/ ./QWebSyphon.app

echo "Compiling binary... ⚙️"
swift build --arch arm64 --arch x86_64 --configuration release

echo "Copying binary and frameworks... 📦"
cp .build/apple/Products/Release/QWebSyphon ./QWebSyphon.app/Contents/MacOS
# ditto keeps the framework's Versions/Current symlinks (cp -r flattens them, which breaks signing)
ditto .build/apple/Products/Release/Syphon.framework ./QWebSyphon.app/Contents/Frameworks/Syphon.framework

echo "Patching runtime path... 🔨"
install_name_tool -change @rpath/Syphon.framework/Versions/A/Syphon @executable_path/../Frameworks/Syphon.framework/Versions/A/Syphon ./QWebSyphon.app/Contents/MacOS/QWebSyphon

echo "Cleaning up... 🧹"
rm -f ./QWebSyphon.app/Contents/MacOS/.gitkeep
rm -f ./QWebSyphon.app/Contents/Frameworks/.gitkeep

echo "Building app icon (Icon Composer)... 🎨"
# app_bundler/QWebSyphon.icon compiles to Assets.car, which macOS 26+ renders with Liquid Glass
# (CFBundleIconName). Older macOS uses QWebSyphon.icns (CFBundleIconFile): actool writes a low-res
# one, so it's replaced with our full-res one (up to 1024), pre-generated by
# scripts/make_app_icon.swift and committed.
# Needs Xcode 26+ actool; without it the app still gets the .icns below.
if ! xcrun actool "$ROOT/app_bundler/QWebSyphon.icon" --compile "$ROOT/QWebSyphon.app/Contents/Resources" --platform macosx \
  --minimum-deployment-target 13.0 --app-icon QWebSyphon \
  --output-partial-info-plist /tmp/qwebsyphon-icon-partial.plist >/dev/null 2>&1; then
  echo "actool could not compile QWebSyphon.icon (needs Xcode 26+); using the .icns only" >&2
fi
cp app_bundler/QWebSyphon.app.skeleton/Contents/Resources/QWebSyphon.icns ./QWebSyphon.app/Contents/Resources/QWebSyphon.icns

echo "Stamping version... 🏷️"
PLIST=./QWebSyphon.app/Contents/Info.plist
# The build number is the commit count, which a shallow clone undercounts.
if [ "$(git rev-parse --is-shallow-repository)" = true ]; then
  echo "Shallow clone: run 'git fetch --unshallow' so the build number is right" >&2
  exit 1
fi
BUILD_NUMBER="$(git rev-list --count HEAD)"
SHORT_VERSION="1.0.$BUILD_NUMBER"
BUILD_DATE="$(date '+%Y-%m-%d %H:%M')"
COMMIT="$(git rev-parse --short HEAD)"
# QWebSyphon.app/ is gitignored, so it never makes the tree look dirty.
[ -n "$(git status --porcelain)" ] && COMMIT="$COMMIT-dirty"
for kv in "CFBundleShortVersionString:$SHORT_VERSION" "CFBundleVersion:$BUILD_NUMBER" "QWSGitCommit:$COMMIT" "QWSBuildDate:$BUILD_DATE"; do
  key="${kv%%:*}"
  value="${kv#*:}"
  /usr/libexec/PlistBuddy -c "Set :$key '$value'" "$PLIST" 2>/dev/null \
    || /usr/libexec/PlistBuddy -c "Add :$key string '$value'" "$PLIST"
done
echo "Built QWebSyphon $SHORT_VERSION ($COMMIT · $BUILD_DATE)"

echo "Signing (ad hoc)... ✍️"
# install_name_tool invalidates the linker's signature; Apple silicon won't run it unsigned
codesign --force --deep --sign - ./QWebSyphon.app

echo "Done! ✅"